x1 = int(input())
y1 = int(input())
x2 = int(input())
y2 = int(input())
x3 = int(input())
y3 = int(input())
x4 = int(input())
y4 = int(input())
left = max(x1, x3)
right = min(x2, x4)
down = max(y1, y3)
up = min(y2, y4)
if(left < right and down < up):
    print((right - left) * (up - down))
else:
    print(0)
